---
name: 🚨 Lint Everything

on:
  merge_group: {}
  pull_request: {}

concurrency:
  group: ${{ github.action }}-${{ github.event.pull_request.id }}
  cancel-in-progress: true
permissions: {}

jobs:
  trunk:
    name: ✅ Validate code quality
    permissions:
      contents: read
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: ⚡️ Run `trunk check`
        uses: trunk-io/trunk-action@e1234e67a86010d61ddac8d8ebf4b783e2ffd2fa # v2.0.0
