---
name: 🚨 Lint Everything

on:
  merge_group: {}
  pull_request: {}

concurrency:
  group: ${{ github.action }}-${{ github.event.pull_request.id }}
  cancel-in-progress: true
permissions: {}

jobs:
  trunk:
    name: ✅ Validate code quality
    permissions:
      contents: read
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: ⚡️ Run `trunk check`
        uses: trunk-io/trunk-action@04ba50e7658c81db7356da96657e6e77f220bfa3 # v1.3.1
