---
name: ♻️ Refresh Trunk cache

on:
  push:
    branches: [main]
    paths: [.trunk/trunk.yaml]

permissions: {}

jobs:
  trunk-cache:
    name: ♻️ Refresh Trunk cache
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: 📦️ Populate cache with Trunk
        uses: trunk-io/trunk-action@e1234e67a86010d61ddac8d8ebf4b783e2ffd2fa # v2.0.0
        with:
          check-mode: populate_cache_only
