---
name: ♻️ Refresh Trunk cache

on:
  push:
    branches: [main]
    paths: [.trunk/trunk.yaml]

permissions: {}

jobs:
  trunk-cache:
    name: ♻️ Refresh Trunk cache
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: 📦️ Populate cache with Trunk
        uses: trunk-io/trunk-action@04ba50e7658c81db7356da96657e6e77f220bfa3 # v1.3.1
        with:
          check-mode: populate_cache_only
