---
name: ♻️ Refresh Trunk cache

on:
  push:
    branches: [main]
    paths: [.trunk/trunk.yaml]

permissions: {}

jobs:
  trunk-cache:
    name: ♻️ Refresh Trunk cache
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: 📦️ Populate cache with Trunk
        uses: trunk-io/trunk-action@04ba50e7658c81db7356da96657e6e77f220bfa3 # v1.3.1
        with:
          check-mode: populate_cache_only
